### ISSUE TITLE
Time to upgrade to ES2015?

### ISSUE THREAD

**Issue by LinusU** [developit/preact-without-babel#2]
Latest Chrome, Firefox, Safari and Edge all support most of ES2015, is it time to upgrade the code base in this repository to reflect that?

This is how I currently use preact, no Babel but still using `const { Component, h, render } = window.preact`, `class _ extends Component`, etc. It would be nice to update here so that I still have something to refer to...

I would be happy to submit a pull request if you feel that this is wanted :)

**Comment by developit** [comment]
@LinusU Personally I'm all for it, but I do want to still have an example of how to use preact with ES3.  Maybe it's worth forking?  We could reverse the names, so the ES2015 native support repo would be `preact-without-babel` and this current repo would become `preact-in-es3` or something.

**Comment by LinusU** [comment]
That sounds awesome! 🙌 

I'll submit a pull request to this repo and you fork this repo to `preact-in-es3`?

**Comment by developit** [comment]
I updated the README and pointed the example to http://jsfiddle.net/developit/e281k4wz/. Thanks!
